// Short set code -> full expansion name, from the reference spreadsheet's
// SetInfo tab (see the dicefight2026-stats-spreadsheet memory for the
// fetch trick). All 48 known sets are included, not just the ones
// currently in the catalog, so this doesn't need revisiting every time a
// new card's set gets added to SampleCards.cs.
export const SET_NAMES: Record<string, string> = {
  PROMO: "Promos from all sets",
  AvX: "Avengers vs. X-Men",
  UXM: "Uncanny X-Men",
  YGO: "Yu-Gi-Oh!",
  BFF: "Battle for Faerûn",
  JL: "Justice League",
  AOU: "Age of Ultron",
  WOL: "War of Light",
  ASM: "The Amazing Spider-Man",
  FUS: "Faerûn Under Siege",
  WF: "World's Finest",
  CW: "Civil War",
  TMNT: "Teenage Mutant Ninja Turtles",
  GAF: "Green Arrow and The Flash",
  DRS: "Doctor Strange",
  DP: "Deadpool",
  HHS: "Heroes in a Half Shell (TMNT)",
  IMW: "Iron Man and War Machine",
  DEF: "Defenders",
  BAT: "Batman",
  SWW: "Superman and Wonder Woman",
  SMC: "Spider-Man Maximum Carnage",
  GOTG: "Guardians of the Galaxy",
  XFC: "X-Men First Class",
  TOA: "Tomb of Annihilation",
  THOR: "The Mighty Thor",
  AI: "Avengers Infinity",
  HQ: "Harley Quinn",
  KI: "Kree Invasion",
  JLL: "Justice Like Lightning",
  BFU: "Battle for Ultramar",
  ORK: "Orks - WAAGH!",
  SW: "Space Wolves - Sons of Russ",
  DOOM: "Doom Patrol",
  JUS: "Justice",
  MYST: "Mystics",
  XMF: "X-Men Forever",
  XFO: "X-Force",
  DXM: "Dark X-Men",
  AIW: "Adventures in Waterdeep",
  TIW: "Trouble in Waterdeep",
  ZHN: "Zhentarim",
  WWE: "WWE",
  TAG: "Tag Teams",
  BIT: "Bitter Rivals",
  IG: "Infinity Gauntlet",
  DPS: "Dark Phoenix Saga",
  SKC: "Superman Kryptonite Crisis",
  MSW: "Marvel Secret Wars",
};
