<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiceFight.Engine\DiceFight.Engine.csproj" />
    <ProjectReference Include="..\DiceFight.DiscordBot\DiceFight.DiscordBot.csproj" />
  </ItemGroup>

</Project>
